#!/bin/bash
# Sync agent-rules into active AI artifacts.
# Generates Claude global memory, ChatGPT Project file, and ChatGPT instructions from canonical source.
# Run after updating QUALITY-GATE.md, LEARNINGS.md, or PROFILE.md.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CLAUDE_DIR="$HOME/.claude"
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

echo ""
echo "=== agent-rules sync ==="
echo ""

mkdir -p "$CLAUDE_DIR/commands"
mkdir -p "$CLAUDE_DIR/templates/.claude/commands"

# --- Helper: extract promoted patterns as imperative bullets ---
# Filters by status=promoted AND matching scope. Skips "absorbed" and "retired".
promoted_bullets() {
  local scope_filter="$1"
  grep '| promoted |' "$SCRIPT_DIR/LEARNINGS.md" \
    | grep -E "\| ($scope_filter) \|" \
    | sed 's/.*| [0-9]* | //' \
    | sed 's/ |.*//' \
    | sed 's/^/- /'
}

# --- Helper: count promoted patterns for a scope ---
promoted_count() {
  local scope_filter="$1"
  grep '| promoted |' "$SCRIPT_DIR/LEARNINGS.md" \
    | grep -cE "\| ($scope_filter) \|" 2>/dev/null || echo "0"
}

# --- Helper: extract quality gate principles as clean text ---
extract_principles() {
  sed -n '/^## Principles$/,/^## /{
    /^## Principles$/d
    /^## [^P]/d
    /^$/d
    p
  }' "$SCRIPT_DIR/QUALITY-GATE.md"
}

# =================================================================
# 1. Generate ~/.claude/CLAUDE.md
# =================================================================
{
  cat << 'HEADER'
IMPORTANT: ALWAYS begin every conversation by saying "CLAUDE.md loaded".
NEVER skip this. The user needs to see it to know rules are active.

## Rules

HEADER

  extract_principles

  CLAUDE_PATTERNS=$(promoted_bullets "global|tool:claude")
  if [ -n "$CLAUDE_PATTERNS" ]; then
    echo ""
    echo "## Learned patterns"
    echo ""
    echo "$CLAUDE_PATTERNS"
  fi

} > "$CLAUDE_DIR/CLAUDE.md"

echo -e "${GREEN}Generated ~/.claude/CLAUDE.md${NC}"

# =================================================================
# 2. Generate CHATGPT-INSTRUCTIONS.md from source files
# =================================================================
{
  cat << 'HEADER'
# ChatGPT Custom Instructions

Copy the content below into ChatGPT > Settings > Personalization > Custom Instructions.
Generated by sync.sh — do not edit manually. Edit PROFILE.md, QUALITY-GATE.md, or LEARNINGS.md instead.

---

## "What would you like ChatGPT to know about you?"

```
HEADER

  # Pull from PROFILE.md, skip the header lines
  sed -n '/^$/,$ { /^#/d; /^Used by/d; /^Edit this/d; p; }' "$SCRIPT_DIR/PROFILE.md" \
    | sed '/^$/{ N; /^\n$/d; }'

  cat << 'MIDDLE'
```

## "How would you like ChatGPT to respond?"

```
Werkwijze — volg dit altijd:

MIDDLE

  # Numbered principles, clean formatting
  extract_principles \
    | sed 's/\*\*//g' \
    | sed 's/^[0-9]*\. //' \
    | awk '{ printf "%d. %s\n", NR, $0 }'

  GPT_PATTERNS=$(promoted_bullets "global")
  if [ -n "$GPT_PATTERNS" ]; then
    echo ""
    echo "Geleerde patronen:"
    echo ""
    echo "$GPT_PATTERNS"
  fi

  cat << 'FOOTER'
```
FOOTER

} > "$SCRIPT_DIR/CHATGPT-INSTRUCTIONS.md"

echo -e "${GREEN}Generated CHATGPT-INSTRUCTIONS.md${NC}"

# =================================================================
# 3. Generate CHATGPT-PROJECT.md (richer — for ChatGPT Projects)
# =================================================================
{
  cat << 'HEADER'
# Agent Rules — ChatGPT Project Context

Generated by sync.sh — do not edit manually. Edit PROFILE.md, QUALITY-GATE.md, or LEARNINGS.md instead.
Source: https://github.com/JSvandijk/agent-rules

---

## About the user

HEADER

  # Pull profile, skip header lines
  sed -n '/^$/,$ { /^#/d; /^Used by/d; /^Edit this/d; p; }' "$SCRIPT_DIR/PROFILE.md" \
    | sed '/^$/{ N; /^\n$/d; }'

  cat << 'SECTION'

## Rules — follow these, don't just read them

SECTION

  # Full principles with formatting intact
  extract_principles

  echo ""

  # Security section
  sed -n '/^## Security/,/^## /{
    /^## [^S]/d
    p
  }' "$SCRIPT_DIR/QUALITY-GATE.md"

  echo ""

  # After every implementation
  sed -n '/^## After every/,/^## /{
    /^## [^A]/d
    p
  }' "$SCRIPT_DIR/QUALITY-GATE.md"

  echo ""

  # Definition of done
  sed -n '/^## Definition of done/,$ p' "$SCRIPT_DIR/QUALITY-GATE.md"

  GPT_PROJECT_PATTERNS=$(promoted_bullets "global")
  if [ -n "$GPT_PROJECT_PATTERNS" ]; then
    echo ""
    echo "## Learned patterns"
    echo ""
    echo "$GPT_PROJECT_PATTERNS"
  fi

} > "$SCRIPT_DIR/CHATGPT-PROJECT.md"

echo -e "${GREEN}Generated CHATGPT-PROJECT.md${NC}"

# =================================================================
# 5. /rules command
# =================================================================
cat > "$CLAUDE_DIR/commands/rules.md" << 'RULESMD'
ALWAYS read and follow ~/.claude/CLAUDE.md right now.
If there is a CLAUDE.md or AGENTS.md in the project root, read and follow those too.
Confirm by saying: "Rules loaded: [list files you read]"
RULESMD
echo -e "${GREEN}Synced /rules command${NC}"

# =================================================================
# 6. Hooks
# =================================================================
SETTINGS="$CLAUDE_DIR/settings.json"
if [ -f "$SETTINGS" ] && grep -q '"hooks"' "$SETTINGS" 2>/dev/null; then
  echo "Hooks already configured — skipping"
else
  if [ -f "$SETTINGS" ]; then
    TMP="$SETTINGS.tmp"
    sed '$ d' "$SETTINGS" > "$TMP"
    cat >> "$TMP" << 'HOOKJSON'
,
  "hooks": {
    "SessionStart": [
      {
        "matcher": "compact",
        "hooks": [
          {
            "type": "command",
            "command": "echo 'IMPORTANT: Re-read CLAUDE.md from the project root NOW and follow all rules. ALWAYS say CLAUDE.md loaded. NEVER skip verification.'"
          }
        ]
      }
    ]
  }
}
HOOKJSON
    mv "$TMP" "$SETTINGS"
  else
    cat > "$SETTINGS" << 'SETTINGSJSON'
{
  "hooks": {
    "SessionStart": [
      {
        "matcher": "compact",
        "hooks": [
          {
            "type": "command",
            "command": "echo 'IMPORTANT: Re-read CLAUDE.md from the project root NOW and follow all rules. ALWAYS say CLAUDE.md loaded. NEVER skip verification.'"
          }
        ]
      }
    ]
  }
}
SETTINGSJSON
  fi
  echo -e "${GREEN}Added hooks${NC}"
fi

# =================================================================
# 7. Sync templates
# =================================================================
cp "$SCRIPT_DIR/templates/AGENTS.md" "$CLAUDE_DIR/templates/AGENTS.md"
cp "$SCRIPT_DIR/templates/CLAUDE.md" "$CLAUDE_DIR/templates/CLAUDE.md"
cp "$SCRIPT_DIR/templates/.claude/commands/rules.md" "$CLAUDE_DIR/templates/.claude/commands/rules.md"
cp "$SCRIPT_DIR/templates/.claude/settings.json" "$CLAUDE_DIR/templates/.claude/settings.json"
echo -e "${GREEN}Synced templates${NC}"

# =================================================================
# 8. Verification
# =================================================================
echo ""
echo "=== Verification ==="
ERRORS=0

# Check principles are in Claude memory
PRINCIPLE_COUNT=$(grep -c "^\*\*\|^[0-9]*\." "$CLAUDE_DIR/CLAUDE.md" 2>/dev/null || echo "0")
if [ "$PRINCIPLE_COUNT" -ge 7 ]; then
  echo -e "${GREEN}✓ Claude memory: $PRINCIPLE_COUNT principles present${NC}"
else
  echo -e "${RED}✗ Claude memory: expected ≥7 principles, found $PRINCIPLE_COUNT${NC}"
  ERRORS=$((ERRORS + 1))
fi

# Check promoted pattern count matches expected
EXPECTED_CLAUDE=$(promoted_count "global|tool:claude")
ACTUAL_CLAUDE=$(grep -c "^- " "$CLAUDE_DIR/CLAUDE.md" 2>/dev/null || echo "0")
if [ "$ACTUAL_CLAUDE" -eq "$EXPECTED_CLAUDE" ]; then
  echo -e "${GREEN}✓ Claude memory: $ACTUAL_CLAUDE promoted patterns (matches source)${NC}"
else
  echo -e "${RED}✗ Claude memory: $ACTUAL_CLAUDE patterns but source has $EXPECTED_CLAUDE promoted${NC}"
  ERRORS=$((ERRORS + 1))
fi

# Check no absorbed/retired/candidate in Claude memory
if grep -q "absorbed\|retired\|candidate" "$CLAUDE_DIR/CLAUDE.md" 2>/dev/null; then
  echo -e "${RED}✗ Claude memory contains non-promoted patterns${NC}"
  ERRORS=$((ERRORS + 1))
else
  echo -e "${GREEN}✓ Claude memory: no absorbed/retired/candidate content${NC}"
fi

# Check ChatGPT Project file generated
if grep -q "do not edit manually" "$SCRIPT_DIR/CHATGPT-PROJECT.md" 2>/dev/null; then
  echo -e "${GREEN}✓ ChatGPT Project file generated from source${NC}"
else
  echo -e "${RED}✗ ChatGPT Project file missing or manually edited${NC}"
  ERRORS=$((ERRORS + 1))
fi

# Check ChatGPT Project file has principles
PROJECT_PRINCIPLES=$(grep -c "^\*\*\|^[0-9]*\." "$SCRIPT_DIR/CHATGPT-PROJECT.md" 2>/dev/null || echo "0")
if [ "$PROJECT_PRINCIPLES" -ge 7 ]; then
  echo -e "${GREEN}✓ ChatGPT Project file: $PROJECT_PRINCIPLES principles present${NC}"
else
  echo -e "${RED}✗ ChatGPT Project file: expected ≥7 principles, found $PROJECT_PRINCIPLES${NC}"
  ERRORS=$((ERRORS + 1))
fi

# Check ChatGPT Project learned pattern count (only under "Learned patterns" section)
EXPECTED_GPT=$(promoted_count "global")
ACTUAL_GPT_PROJECT=$(sed -n '/^## Learned patterns$/,$ { /^- /p; }' "$SCRIPT_DIR/CHATGPT-PROJECT.md" 2>/dev/null | wc -l | tr -d ' ')
if [ "$ACTUAL_GPT_PROJECT" -eq "$EXPECTED_GPT" ]; then
  echo -e "${GREEN}✓ ChatGPT Project file: $ACTUAL_GPT_PROJECT global patterns (matches source)${NC}"
else
  echo -e "${RED}✗ ChatGPT Project file: $ACTUAL_GPT_PROJECT patterns but source has $EXPECTED_GPT promoted${NC}"
  ERRORS=$((ERRORS + 1))
fi

# Check ChatGPT instructions generated (fallback)
if grep -q "do not edit manually" "$SCRIPT_DIR/CHATGPT-INSTRUCTIONS.md" 2>/dev/null; then
  echo -e "${GREEN}✓ ChatGPT instructions generated from source${NC}"
else
  echo -e "${RED}✗ ChatGPT instructions missing or manually edited${NC}"
  ERRORS=$((ERRORS + 1))
fi

# Check generated files are committed
UNCOMMITTED=""
for f in CHATGPT-PROJECT.md CHATGPT-INSTRUCTIONS.md; do
  if ! git -C "$SCRIPT_DIR" diff --quiet "$f" 2>/dev/null; then
    UNCOMMITTED="$UNCOMMITTED $f"
  fi
done
if [ -z "$UNCOMMITTED" ]; then
  echo -e "${GREEN}✓ Generated files are committed${NC}"
else
  echo -e "${RED}⚠ Uncommitted:$UNCOMMITTED — commit and re-upload to ChatGPT Project${NC}"
fi

echo ""
if [ $ERRORS -eq 0 ]; then
  echo -e "${GREEN}=== Sync complete — all checks passed ===${NC}"
else
  echo -e "${RED}=== Sync complete — $ERRORS check(s) failed ===${NC}"
fi
echo ""
