#!/bin/bash
# Sync agent-rules into active AI artifacts.
# Generates Claude global memory AND ChatGPT instructions from canonical source.
# Run after updating QUALITY-GATE.md or LEARNINGS.md.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CLAUDE_DIR="$HOME/.claude"
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

echo ""
echo "=== agent-rules sync ==="
echo ""

mkdir -p "$CLAUDE_DIR/commands"
mkdir -p "$CLAUDE_DIR/templates/.claude/commands"

# --- Helper: extract promoted patterns as imperative bullets ---
promoted_bullets() {
  local scope_filter="$1"  # "global" or "tool:claude" or "global|tool:claude"
  grep '| promoted |' "$SCRIPT_DIR/LEARNINGS.md" \
    | grep -E "\| ($scope_filter) \|" \
    | sed 's/.*| [0-9]* | //' \
    | sed 's/ |.*//' \
    | sed 's/^/- /'
}

# =================================================================
# 1. Generate ~/.claude/CLAUDE.md
# =================================================================
{
  cat << 'HEADER'
IMPORTANT: ALWAYS begin every conversation by saying "CLAUDE.md loaded".
NEVER skip this. The user needs to see it to know rules are active.

## Rules

HEADER

  # Extract principles from QUALITY-GATE.md as numbered ALWAYS/NEVER rules
  sed -n '/^## Principles$/,/^## /{
    /^## Principles$/d
    /^## [^P]/d
    /^$/d
    p
  }' "$SCRIPT_DIR/QUALITY-GATE.md"

  echo ""
  echo "## Learned patterns"
  echo ""

  # Only promoted + global or tool:claude patterns, as bullets
  promoted_bullets "global|tool:claude"

} > "$CLAUDE_DIR/CLAUDE.md"

echo -e "${GREEN}Generated ~/.claude/CLAUDE.md (rules + promoted patterns)${NC}"

# =================================================================
# 2. Generate CHATGPT-INSTRUCTIONS.md
# =================================================================
{
  cat << 'HEADER'
# ChatGPT Custom Instructions

Copy the content below into ChatGPT > Settings > Personalization > Custom Instructions.
Generated by sync.sh from QUALITY-GATE.md and LEARNINGS.md — do not edit manually.

---

## "What would you like ChatGPT to know about you?"

```
Ik evalueer AI-output streng op: security, consistentie tussen code/docs/claims,
deprecated API-gebruik, dead code, git-hygiëne, en of "klaar" ook echt klaar is.

Ik heb liever 3 goed gecontroleerde outputs dan 10 ongecontroleerde.
Voeg geen extra documenten, secties of features toe die ik niet heb gevraagd.
Als iets niet geverifieerd is, zeg dat — verzin geen zekerheid.

Ik werk met Claude Opus als second opinion. Wees minstens zo streng op jezelf
als een externe reviewer zou zijn.

Feedback repo: https://github.com/JSvandijk/agent-rules
```

## "How would you like ChatGPT to respond?"

```
Werkwijze — volg dit altijd:

HEADER

  # Generate numbered rules from QUALITY-GATE principles
  sed -n '/^## Principles$/,/^## /{
    /^## Principles$/d
    /^## [^P]/d
    /^$/d
    p
  }' "$SCRIPT_DIR/QUALITY-GATE.md" \
    | sed 's/\*\*//g' \
    | sed 's/^[0-9]*\. //' \
    | nl -ba -s '. '

  echo ""
  echo "Geleerde patronen:"
  echo ""

  # Only promoted + global patterns for ChatGPT (not tool:claude)
  promoted_bullets "global"

  cat << 'FOOTER'
```
FOOTER

} > "$SCRIPT_DIR/CHATGPT-INSTRUCTIONS.md"

echo -e "${GREEN}Generated CHATGPT-INSTRUCTIONS.md (rules + global patterns)${NC}"

# =================================================================
# 3. /rules command
# =================================================================
cat > "$CLAUDE_DIR/commands/rules.md" << 'RULESMD'
ALWAYS read and follow ~/.claude/CLAUDE.md right now.
If there is a CLAUDE.md or AGENTS.md in the project root, read and follow those too.
Confirm by saying: "Rules loaded: [list files you read]"
RULESMD
echo -e "${GREEN}Synced ~/.claude/commands/rules.md${NC}"

# =================================================================
# 4. Hooks
# =================================================================
SETTINGS="$CLAUDE_DIR/settings.json"
if [ -f "$SETTINGS" ] && grep -q '"hooks"' "$SETTINGS" 2>/dev/null; then
  echo "Hooks already configured — skipping"
else
  if [ -f "$SETTINGS" ]; then
    TMP="$SETTINGS.tmp"
    sed '$ d' "$SETTINGS" > "$TMP"
    cat >> "$TMP" << 'HOOKJSON'
,
  "hooks": {
    "SessionStart": [
      {
        "matcher": "compact",
        "hooks": [
          {
            "type": "command",
            "command": "echo 'IMPORTANT: Re-read CLAUDE.md from the project root NOW and follow all rules. ALWAYS say CLAUDE.md loaded. NEVER skip verification.'"
          }
        ]
      }
    ]
  }
}
HOOKJSON
    mv "$TMP" "$SETTINGS"
  else
    cat > "$SETTINGS" << 'SETTINGSJSON'
{
  "hooks": {
    "SessionStart": [
      {
        "matcher": "compact",
        "hooks": [
          {
            "type": "command",
            "command": "echo 'IMPORTANT: Re-read CLAUDE.md from the project root NOW and follow all rules. ALWAYS say CLAUDE.md loaded. NEVER skip verification.'"
          }
        ]
      }
    ]
  }
}
SETTINGSJSON
  fi
  echo -e "${GREEN}Added hooks${NC}"
fi

# =================================================================
# 5. Sync templates
# =================================================================
cp "$SCRIPT_DIR/templates/AGENTS.md" "$CLAUDE_DIR/templates/AGENTS.md"
cp "$SCRIPT_DIR/templates/CLAUDE.md" "$CLAUDE_DIR/templates/CLAUDE.md"
cp "$SCRIPT_DIR/templates/.claude/commands/rules.md" "$CLAUDE_DIR/templates/.claude/commands/rules.md"
cp "$SCRIPT_DIR/templates/.claude/settings.json" "$CLAUDE_DIR/templates/.claude/settings.json"
echo -e "${GREEN}Synced templates${NC}"

# =================================================================
# 6. Verify
# =================================================================
echo ""
echo "=== Verification ==="
ERRORS=0

# Check Claude memory contains principles
if grep -q "Verify before claiming done" "$CLAUDE_DIR/CLAUDE.md" 2>/dev/null; then
  echo -e "${GREEN}✓ Claude memory contains quality gate principles${NC}"
else
  echo -e "${RED}✗ Claude memory missing quality gate principles${NC}"
  ERRORS=$((ERRORS + 1))
fi

# Check Claude memory contains promoted patterns
if grep -q "Learned patterns" "$CLAUDE_DIR/CLAUDE.md" 2>/dev/null; then
  echo -e "${GREEN}✓ Claude memory contains promoted patterns${NC}"
else
  echo -e "${RED}✗ Claude memory missing promoted patterns${NC}"
  ERRORS=$((ERRORS + 1))
fi

# Check ChatGPT instructions were generated
if grep -q "Generated by sync.sh" "$SCRIPT_DIR/CHATGPT-INSTRUCTIONS.md" 2>/dev/null; then
  echo -e "${GREEN}✓ ChatGPT instructions generated from source${NC}"
else
  echo -e "${RED}✗ ChatGPT instructions not generated or manually edited${NC}"
  ERRORS=$((ERRORS + 1))
fi

# Check no retired/candidate patterns leaked into Claude memory
if grep -q "candidate\|retired" "$CLAUDE_DIR/CLAUDE.md" 2>/dev/null; then
  echo -e "${RED}✗ Claude memory contains non-promoted patterns${NC}"
  ERRORS=$((ERRORS + 1))
else
  echo -e "${GREEN}✓ Claude memory only contains promoted patterns${NC}"
fi

echo ""
if [ $ERRORS -eq 0 ]; then
  echo -e "${GREEN}=== Sync complete — all checks passed ===${NC}"
else
  echo -e "${RED}=== Sync complete — $ERRORS check(s) failed ===${NC}"
fi
echo ""
